### ISSUE TITLE
What is the difference with postcss-nested

### ISSUE THREAD

**Issue by ai** [jonathantneal/postcss-nesting#1]
We need to clear it in README

**Comment by MoOx** [comment]
You just didn't read the code enough. It's  current tabatkins proposal

http://discourse.specifiction.org/t/css-nesting-specification/839

**Comment by ai** [comment]
We need to tell about different syntax with double `{ {` explicitly, right now it is easy to miss this difference

**Comment by MoOx** [comment]
I think people should just read & will see when they will try

See https://github.com/jonathantneal/postcss-nesting/pull/3

**Comment by ai** [comment]
It is easy to miss something when you didn't expect it. For example, I expected a Sass syntax or old tabatkins syntax, so I miss extra `{` lines.

Other users will do it too and then will ask "why plugin is not working".

**Comment by ai** [comment]
@jonathantneal that sentence didn't tell *the difference*, it tell only about author. And there is very easy to miss extra { lines, because many users are not expected them in code (our eyes can see only what we expect).

We need clear sentence like "Instead of postcss-nested this plugin uses latest tabaskin proposal with extra { in nested rules".

**Comment by MoOx** [comment]
I think those 2 plugins are pretty clear about what they does from each short description. One contains "Sass", the other "W3C". People will ask themselves "what is the difference between those 2 ?" and check more than 20 secondes :) They are not stupid.
Maybe if some people really open issue for that, @jonathantneal might reconsider this issue.

**Comment by ai** [comment]
You are know the difference between specs, so you can find that extra line. I didn't know about latest spec, so I miss it.

Put yourself in difference minds:

Some user will find this plugin in Google, he will see "nesting" word and he well not think about difference, because in preprocessor there is only one nesting ;-).

**Comment by ai** [comment]
20 seconds is to long time for our generation ;-).

BTW, do you saw a psychology experiment when people miss a gorilla in the center of image?
http://www.theinvisiblegorilla.com/gorilla_experiment.html

**Comment by MoOx** [comment]
Haha, yes I saw it already. Good point ^^

**Comment by ai** [comment]
I mentioned postcss-nesting in postcss-nested.

**Comment by tadasajon** [comment]
Could someone please link to a clear explanation of the difference?  I have no idea why there is both a `postcss-nesting` and also a `postcss-nested`.  It is confusing for me.

**Comment by ai** [comment]
@tadasajon `postcss-nested` use Sass syntax. `postcss-nesting` uses syntax from CSS Nested spec draft.

The syntaxes are different.

@jonathantneal Maybe we should explain it in docs?
