### ISSUE TITLE
Support direct nesting

### ISSUE THREAD

**Issue by MadLittleMods** [jonathantneal/postcss-nesting#10]
Add support for the use of the `&` by itself (without `@nest` rule): http://tabatkins.github.io/specs/css-nesting/#direct-nesting

> nesting selector, written as an ASCII ampersand &.

> A style rule can be directly nested within another style rule if its selector is nest-prefixed.

**Comment by jonathantneal** [comment]
Thanks for making an issue for this, @MadLittleMods. Yes, the spec allows for direct nesting, meaning no `@nest` at rule, but only when the explicit `&` is the first character.

**Comment by tbremer** [comment]
I can make PR request for this if it's something you are interested in supporting…

**Comment by jonathantneal** [comment]
I would be. I may not have the time to make it myself in the next day or two.

**Comment by tbremer** [comment]
I have a working solution, I based my tests on the `basic` version, there are some slight stylistic differences in the outputted CSS, optional semicolons & curly brace tab depth. (Image of diff attached).

Do you want me to resolve these issues so the output CSS is exactly the same? Or is this good?

![screen shot 2015-11-09 at 2 15 44 pm](https://cloud.githubusercontent.com/assets/2998575/11045371/bcf006ce-86ec-11e5-8233-1450daf8d222.png)

**Comment by MichielBijl** [comment]
+1
