### ISSUE TITLE
Is it possible to use this with attribute selectors?

### ISSUE THREAD

**Issue by gausie** [jonathantneal/postcss-nesting#18]
I'm trying to do this:
```css
@nest [class^=&] {
```
but that includes the leading `.` from the classname. Is there any way around this?

**Comment by woble** [comment]
Unlikely because `&` equals whatever the selector is, e.g. `.foo {}`, `foo {}`.

You can work around it by writing this:
```
foo {
    @nest .& {
        color: red;
    }

    @nest [class=^'&'] {
        color: cyan;
    }
}
```

**Comment by jonathantneal** [comment]
Thanks for that, @woble. Yes, that would be a solid workaround.
