### ISSUE TITLE
Move to PostCSS org

### ISSUE THREAD

**Issue by MoOx** [jonathantneal/postcss-nesting#2]
I think you did great plugins that transform W3C compliant code and I think it would be nice to have them under the postcss org. Are you open to be added in this org & move some in there ?
poke @ai

**Comment by ai** [comment]
Right now I didn't understand a difference with postcss-nested :-)

**Comment by MoOx** [comment]
This one follow the tabatkins proposal http://discourse.specifiction.org/t/css-nesting-specification/839

**Comment by ai** [comment]
Nope, Tabatkins spec has different syntax.

**Comment by MoOx** [comment]
Not from what I can read http://tabatkins.github.io/specs/css-nesting/#the-nested-block

**Comment by ai** [comment]
Yeap, my mistake, I miss extra { line

**Comment by jonathantneal** [comment]
Any interest in this still? You’ve had a few more months to review my work.

**Comment by MoOx** [comment]
a "w3c" compliant plugin should be there 👌🏼

**Comment by tbremer** [comment]
I agree with this! :+1:

**Comment by MoOx** [comment]
I guess you won't do it...

**Comment by jonathantneal** [comment]
I’m open to moving this. I was actually seeking approval from the rest of the team. If you’re good with it, @MoOx, I’ll move it over before the next release.

**Comment by MoOx** [comment]
I am not invested that much in postcss community, you can see that with @ai or others :)
