### ISSUE TITLE
Why no Sass-style nesting?

### ISSUE THREAD

**Issue by eriklharper** [jonathantneal/postcss-nesting#29]
In the Sass world, nesting works like this:
```
.parent {
    .child {
        font-size: 12px;
    }
}
```
which compiles to:
```
.parent .child { font-size: 12px; }
```
Why doesn't `postcss-nesting` support this?  Or the better question is why doesn't the CSS nesting spec support this style of writing nested selectors?  And yes, [I've read the spec and its explanation for this being that its because it would create an unbounded lookahead](https://tabatkins.github.io/specs/css-nesting/#nesting), but I still wonder why there can't be a PostCSS plugin that implements this style of nesting?

The specific use case where this type of nesting is useful is for example when you import a global vendor stylesheet, such as bootstrap or icomoon and you want to nest those "global" styles inside of your app component's class name so that it "namespaces" the global vendor styles and scopes them to the specific component you need those styles for.

With `postcss-nesting` this isn't possible unless the vendor stylesheet is modified to add `&` in front of every single class name, which defeats the purpose of installing that vendor stylesheet and using as-is.

**Comment by Semigradsky** [comment]
https://github.com/postcss/postcss-nested
?

**Comment by eriklharper** [comment]
Yes, I came across this just now, and it works as I expect, thanks! @Semigradsky
