### ISSUE TITLE
Latest release confusion

### ISSUE THREAD

**Issue by woble** [jonathantneal/postcss-nesting#36]
@jonathantneal 
Could you clarify what the latest release is?

[npm](https://www.npmjs.com/package/postcss-nesting) says `4.0.1` but `npm i postcss-nesting` installs `2.3.1`, which is the latest release here on github. Was there a rollback at some point?

Judging from the issue #35, it's not entirely ready for production as it breaks certain use cases.

**Comment by jonathantneal** [comment]
@woble, the latest release at the time of this message is 4.0.1.

https://github.com/jonathantneal/postcss-nesting/blob/master/package.json#L3

If you’re installing 2.3.1, then you are using a very old version.
