### ISSUE TITLE
Nesting issues 4.1.0

### ISSUE THREAD

**Issue by woble** [jonathantneal/postcss-nesting#46]
4.1.0 seems to solve most issues, but now something else doesn't work. Unsure if according with spec. It worked prior v3 though.

The following does not compile at all. Using `postcss-selector-matches` to unfold `matches` in the example; does not affect the `postcss-nesting` processing as `& + &` is expected to work.

```
li {
    color: cyan;

    /* Basic */
    & + & {
        color: tomato;
    }

    /* Complex */
    &:nth-last-child(n+2):matches(:first-child, :first-child ~ &) {
        color: red;
    }
}
```

Expected

```
li {
    color: cyan;
}

li + li {
    color: tomato;
}

li:nth-last-child(n+2):first-child,
li:nth-last-child(n+2):first-child ~ li {
    color: red;
}
```

**Comment by jonathantneal** [comment]
This is on purpose, as `&` does not merely represent string concatenation. See this comment from the author of the spec: https://github.com/jonathantneal/postcss-nesting/issues/17#issuecomment-217303404

**Comment by JLHwung** [comment]
`& + &` is invalid according to the author (https://github.com/jonathantneal/postcss-nesting/issues/17#issuecomment-221742580). The idea is that `&` is not a selector but the element itself.

This opens to a case where
```css
ol {
    &.li + &.li {
        margin-top: 5px;
    }
}
```
should be valid according to the spec. But as the author said (https://github.com/jonathantneal/postcss-nesting/issues/17#issuecomment-222052927), it is relatively rare and polyfilling this would need greater even expensive efforts, so we simply reject multiple `&` occurence in a complex selector.
