### ISSUE TITLE
'& + &' cannot work in current version (4.2.1)

### ISSUE THREAD

**Issue by superSamChow** [jonathantneal/postcss-nesting#49]
when I upgraded postcss-cssnext (which contains postcss-nesting) to version 3.0.2  for my project, I found this issue.

when use postcss-cssnext 2.9.0 , all work well.

**Comment by mkhazov** [comment]
I have the same issue. How have you solved it?

**Comment by jonathantneal** [comment]
The reason that doesn’t work is because the nesting selector does not represent the parent selector string. It represents the collection of elements.

> the nesting selector represents the elements matched by the parent rule
> — https://tabatkins.github.io/specs/css-nesting/#nest-selector

So, `& ~ &` is like saying “match this particular div when it is a sibling after itself”
