### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by equinusocio** [jonathantneal/postcss-nesting#60]
Hi @jonathantneal, i can't figure out if this expresion `& + &` works with this plugin. Take this example:

```pcss
  .NagivationItem {
    color: var(--foregroundColor, #000);
    text-decoration: none;

    /* & + .Class works as expected but not this ...
       It should be .NagivationItem + .NagivationItem {}, got:
        .NagivationItem { & + & {..} }   
    */
    & + & {
      margin-left: 90px; 
    }
  }
```

**Comment by jonathantneal** [comment]
I’m sorry for the delayed response. The nesting defined by the CSSWG is not the same as the nesting in Sass.

In CSS, the `&` selector represents an Element. It does not represent a selector string, as it did in Sass.

Writing `& + &` is like writing “_match an Element that comes after itself_”, which is not possible.
