### ISSUE TITLE
TypeError: parent.before is not a function

### ISSUE THREAD

**Issue by AndrewStobie** [jonathantneal/postcss-nesting#61]
When I go to build with postcss-nesting in my `postcss.config.js`

I get an error of:

```
TypeError: parent.before is not a function
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

with my package.json containing:

`"postcss": "7.0.3",
    "postcss-color-function": "^4.0.1",
    "postcss-custom-media": "7.0.4",
    "postcss-custom-properties": "^8.0.6",
    "postcss-flexbugs-fixes": "^4.1.0",
    "postcss-loader": "^3.0.0",
    "postcss-mixins": "^6.2.0",
    "postcss-nesting": "^7.0.0",
    "postcss-sorting": "^4.0.0",
`

when I take out postcss-nesting it builds fine.

**Comment by jonathantneal** [comment]
I’m sorry you’re having this issue. Would you please be able to put together a small repository that recreates the issue? Unfortunately, I would not be able to figure out which plugin (postcss-nesting or otherwise) against which combination of css causes this issue.

**Comment by jonathantneal** [comment]
Closing due to a week of inactivity.
