### ISSUE TITLE
Can i nest a tag inside a class?

### ISSUE THREAD

**Issue by simonh1000** [jonathantneal/postcss-nesting#66]
I'm asking because the docs don't include an example like this, which is influenced by my scss experience.
```
.icon-container {
    width: 202px;
    img {
        max-width: 80%;
    }
}
```

what I'm seeing is
![image](https://user-images.githubusercontent.com/5256724/67160593-c9cc7b80-f352-11e9-9a75-0ab7d986d66a.png)

**Comment by ian-pvd** [comment]
Hi @simonh1000, 

Have you tried the following?
```
.icon-container {
    width: 202px;
    & img {
        max-width: 80%;
    }
}
```

This would be equivalent to:
```
.icon-container {
    width: 202px;
}

.icon-container img {
    max-width: 80%;
}
```

**Comment by simonh1000** [comment]
ah, thanks for the tip - I was using what I knew to work from SCSS
